import Head from 'next/head'
import { usePokemonState } from '../src/state'
import styles from '../styles/Home.module.css'

const Loading = ({ status }) => <span>Loading: {status.toString()}</span>

const PokeLen = ({ pokelen }) => <span>pokeLen: {pokelen}</span>

const PokeFetchButton = ({ onClick, children }) => (
  <button onClick={onClick}>{children}</button>
)

const PokeList = ({ flyingPokemon }) => (
  <ul>
    {flyingPokemon.map(({ pokemon }) => (
      <li key={pokemon.name}>{pokemon.name}</li>
    ))}
  </ul>
)

function PokemonList() {
  const fetchPokemon = usePokemonState((state) => state.fetchPokemon)
  const flyingPokemon = usePokemonState((state) => state.flyingPokemon)
  const status = usePokemonState((state) => state.loading)
  return (
    <>
      <Loading status={status.toString()} />
      <PokeLen pokelen={flyingPokemon.length} />
      <PokeFetchButton onClick={fetchPokemon}>Get Pokes</PokeFetchButton>
      <PokeList flyingPokemon={flyingPokemon.slice(0, 10)} />
    </>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonList />
    </div>
  )
}
